version: '3'

services:
  server:
    container_name: server
    build: '.'
    volumes:
      - ./:/node-app
      - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '9000:9000'

  db:
    image: 'mongo'
    container_name: mongodb
    ports:
      - '27018:27018'
    volumes:
      - ./data/db:/data/db